var buttonColours = ["green", "red", "blue", "yellow"];
var autoPressed = [];
var userPressed = [];
var level = 0;
// var started= false;
var startclick = false;

// Function For random colour generated by computer
function randomColourOutput() {
  //clearing userPressed color array
  userPressed=[];
  level++;
  $("#level-title").text("Level " + level);
  //generating random number and assign it, to index
  // of button colour
  var randomNum = Math.floor(Math.random() * 4);
  var randomColour = buttonColours[randomNum];

  soundOnBtn(randomColour);
  animationOnBtn(randomColour);
  //pushing random colour in autoPressed array
  autoPressed.push(randomColour);
  console.log(randomNum);
  console.log(autoPressed);
}


// this is for when key is pressed then only randomColourOutput
// function should called and once if condition is flase
// then randomColourOutput will never called on keydown

$(document).click(function() {
  // !started will return true and it satisfy if condition

    if (!startclick) {
      randomColourOutput();
      startclick = true;
    }
});
// user generated colour function on click
$(".btn").click(function() {
  //storing id value of clicked button in this variable
  var userChosenColour = $(this).attr("id");
  btnPressed(userChosenColour);

});

// for char pressing
$(document).keydown(function() {
  wesd(event.key);
});

// for char pressed in keyboard for switch case
function btnPressed(color) {
  var userChosenColour = color;
  //pusing clicked colour by user in userPressed
  userPressed.push(userChosenColour);
  soundOnBtn(userChosenColour);
  animationOnBtn(userChosenColour);
  console.log(userPressed);
  //this function is called, to check weahther userPressed and autoPressed
  // have same array
  //length-1 because to catch current index
  checkAnswer(userPressed.length-1);
}

function wesd (key) {
  switch(key) {
    case "w":
    btnPressed("green");
    break;

    case "e":
    btnPressed("yellow");
    break;

    case "s":
    btnPressed("red");
    break;

    case "d":
    btnPressed("blue");
    break;

    default:
    console.log(this.innerHTML);
  }
}

//function for sounds
function soundOnBtn(name) {
  var sound = new Audio("sounds/" + name + ".mp3");
  sound.play();
}

//function for animation on buttons
function animationOnBtn(name) {
  $("#" + name).addClass("pressed");
  setTimeout(function() {
    $("#" + name).removeClass("pressed");
  }, 100);
  $("#" + name).fadeOut(100).fadeIn(100);
}

//to check weahther userPressed and autoPressed
// have same array
function checkAnswer(currentLevel) {
  // checking current index's color pressed by user is equal to
  // autoPressed index's color
  if (autoPressed[currentLevel] === userPressed[currentLevel]) {
    // checking weather length of bot array in same
    if (autoPressed.length === userPressed.length) {
      // if yes call randomColourOutput function after 1 sec
      setTimeout(function() {
        randomColourOutput();
      }, 1000);
    }
  }
    else {
      console.log("wrong");
      soundOnBtn("wrong");
      //it will add class to body for 2sec
      $("body").addClass("game-over")
      setTimeout(function() {
        $("body").removeClass("game-over")
      }, 100);
      $("h1").html("Game Over, <span>Click Me</span> to Restart");
      //as we press wrong key this function will reset the game.
      setTimeout(function() {
        reset();
      },1000);

    }
  }

// to reset the game and when user will click any button then it will
// call line no 29
function reset() {
  level =0;
  autoPressed = [];
  // started = false;
  startclick = false;
}
